### ISSUE TITLE
use diffraction-limit image as PSF basis function

### ISSUE THREAD

**Issue by davidwhogg** [davidwhogg/TheThresher#23]
Right now the PSF is modeled as a mixture of narrow Gaussians.  It _should_ be modeled as a mixture of Airy functions, where the Airy function is the FFT of the entrance aperture, scaled for f ratio, wavelength and so on.  that would get the airy rings out of the scene image.

**Comment by davidwhogg** [comment]
see email from fed on 2012-04-30 giving telescope specs

**Comment by dfm** [comment]
won't fix
