### ISSUE TITLE
Come up with a better name.

### ISSUE THREAD

**Issue by dfm** [davidwhogg/TheThresher#27]

**Comment by fedhere** [comment]
i was just thinking that!
what comes to mind to me is that we are making our own luck with
deconvolution

On Thu, May 3, 2012 at 12:57 PM, Dan Foreman-Mackey <
reply@reply.github.com

> wrote:
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/davidwhogg/LuckyImaging/issues/27

## 

---

federica bianco
UCSB-Las Cumbres Observatory
Global Telescope Network
6740 Cortona Dr, Suite 102         |  /
Goleta, CA                                    |/
                                                     |
*LCOGT.net \*                                 o\
http://secure.lcogt.net/user/fbianco/dev/

---

 /|/\
   |\*  Please consider the environment before printing this e-mail

**Comment by davidwhogg** [comment]
My current contender is "plucky imaging".

**Comment by davidwhogg** [comment]
"patient imaging" "conservative imaging" "fast imaging" "freckle imaging"

**Comment by drphilmarshall** [comment]
I always wanted to press a button marked "ENHANCE" and see a sharpened up image. 

"No Images Left Behind" but its a terrible acronym. Limbo?

**Comment by dfm** [comment]
Hogg's friend suggested "The Combine" http://bit.ly/JICGzn

**Comment by drphilmarshall** [comment]
Haha :-) Incredibly, this song about combine harvesters spent 2 weeks at No. 1 in the charts in the UK in 1976: http://www.youtube.com/watch?v=kAh_A7N3_mc

**Comment by dfm** [comment]
Which charts? I don't believe it!

Also, that is amazing.

**Comment by davidwhogg** [comment]
antonyms of "lucky" include "hapless" and "star-crossed"!

synonyms of "lucky" include "auspicious" and "propitious" and "hot".

**Comment by davidwhogg** [comment]
Oh and another option is the "catholic", "inclusive", "ecumenical", and "tolerant".

**Comment by drphilmarshall** [comment]
Any of these would make excellent acronym padding, if you want to return to the last decade's practices. 
Other words that may evoke the right gut response: thrifty, total, complete, exhaustive, uncompromising, optimal. I rule out the last one as a lesson to others. Total Imaging?

BTW I cannot hear the word "ecumenical" without thinking of cult classic Irish sitcom "Father Ted":

http://video.google.co.uk/videoplay?docid=-6765799421338733335

**Comment by davidwhogg** [comment]
I am currently leaning towards Thrifty Imaging

**Comment by davidwhogg** [comment]
I thesaurused "sharp" and got Keen Imaging.

**Comment by davidwhogg** [comment]
I read up on combine harvesters and came up with The Thresher?

**Comment by davidwhogg** [comment]
Okay, this issue is now closed.
