### ISSUE TITLE
zeros_like issue on broiler?

### ISSUE THREAD

**Issue by davidwhogg** [davidwhogg/TheThresher#3]
I get  this error:  Is it a version issue?  If so, lets upgrade broiler or fix the code.

```
 dwh2@broiler:~/LuckyImaging/code$ python lucky.py
 [ . . . ]
 Traceback (most recent call last):
   File "lucky.py", line 172, in <module>
     unit_tests()
   File "lucky.py", line 151, in unit_tests
     psfMatrix = image2matrix(psf, scene.shape)
   File "lucky.py", line 71, in image2matrix
     rows = np.zeros_like(vals, dtype=int)
 TypeError: zeros_like() got an unexpected keyword argument 'dtype'
```

**Comment by dfm** [comment]
It is a version issue. That kwarg is new in numpy 1.6.x and the system has version 1.3, I think. I'll look into upgrading the system version tomorrow.

**Comment by dfm** [comment]
Use a virtual environment instead...

https://github.com/davidwhogg/LuckyImaging/wiki/Setting-up-a-virtual-environment
