### ISSUE TITLE
Clean up plots of inference steps

### ISSUE THREAD

**Issue by dfm** [davidwhogg/TheThresher#31]
We need to decide exactly what to plot. Also, in the new version of the code, I'm only saving the _current_ scene (not the previous one) so we can't plot all the same panels as before. I think that this is probably ok but I'm willing to negotiate.

**Comment by davidwhogg** [comment]
That is all fine.  We should, however, save the thisScene as well as newScene, so we can see what the "derivative" is in scene space.  This will also be necessary if we move to a map-reduce framework.
