### ISSUE TITLE
fftconvolve instead of convolve

### ISSUE THREAD

**Issue by fedhere** [davidwhogg/TheThresher#32]
is there a reason why you use scipy.signal.convolve instead of scipy.signal.fftconvolve? as we deal with relatively large arrays this simple change speeds up the code by a factor ~2 running with 2 passes on 10 images... with nearly identical final result (numerical differences)

**Comment by dfm** [comment]
This seems like a good suggestion. The problem for me is that when I switch over to `fftconvolve`, I get a `segfault` on OS X Lion with `scipy==0.10.1`.

**Comment by dfm** [comment]
Never mind... it's a known problem. I compiled scipy with `llvm-gcc` which is known not to work so I recompiled and everything's working now.

**Comment by davidwhogg** [comment]
done, or so DFM says
