### ISSUE TITLE
measure resolution and s/n

### ISSUE THREAD

**Issue by davidwhogg** [davidwhogg/TheThresher#50]
The paper makes claims about resolution and s/n.  We have to be able to measure these in an image!!

**Comment by davidwhogg** [comment]
roughly speaking, the S/N code should be:

Put a quasi-circular 5-pixel-ish diameter aperture on the (a) bright source, (b) the faint source, and (c) 100 random locations.  At each location, make a sky-subtracted (just subtract the median of the whole image, perhaps?) measure of the signal at that location.  Call the "noise" the sigma-clipped (or go crazier if you want to!) rms of the 100 randoms.  Sigma-clip pretty hard.

This will give s/n in the bright source, and s/n in the faint source, both of which matter.

**Comment by davidwhogg** [comment]
roughly speaking, the resolution code should be:

Fit a single multivariate Gaussian to the image, possibly just in the 5x5 or 7x7-pixel region of the brightest source.  Report the variance tensor and/or its determinant

**Comment by dfm** [comment]
Here's a first pass at the S/N calculation. It's not quite right yet but it's a start:

https://github.com/davidwhogg/TheThresher/blob/107aac07d7d5e98182b6f50316759f454afaa328/thresher/utils.py#L21

**Comment by davidwhogg** [comment]
Let's start with that!  It will work for the bright source but not for the faint source, because when it does the faint source, the sky apertures will hit the bright source and throw the RMS.  Really we should do a true sky noise estimate and use that directly.
