### ISSUE TITLE
don't photometer sources outside the data

### ISSUE THREAD

**Issue by davidwhogg** [davidwhogg/TheThresher#60]
The scene is bigger than the data.  We should only consider sources within the data region!

**Comment by drphilmarshall** [comment]
Are sources appearing outside the data region a sign of faulty regularisation?

On Sun, Jun 17, 2012 at 6:55 AM, David W. Hogg
reply@reply.github.com
wrote:

**Comment by dfm** [comment]
Nope. It's mostly a sign of bad alignment of the data (another high priority). If the data are poorly aligned, the inferred PSF is offset. This causes the data to provide constraints on sources that are naively outside bounds of the data.

**Comment by dfm** [comment]
done.
