### ISSUE TITLE
add command-line arguments that allow us to adjust alpha

### ISSUE THREAD

**Issue by davidwhogg** [davidwhogg/TheThresher#79]
I think we want something like

```
--alpha-numerator 2.0 --alpha-denominator 8.0
```

and then have

```
alpha = alpha_numerator / (iteration + alpha_denominator)
```

in the code for the first pass.

Then we also need command-line

```
--number-of-passes 3
```

to control the number of passes we take over the data.

Then I will get Ekta (or someone) to run a grid of tests on, say, the triple data.  Or NGC 3603

**Comment by dfm** [comment]
Done. The command line arguments are called `alpha` and `beta` and they resolve to

```
learning_rate = alpha / (beta + iteration)
```

for the first pass and:

```
learning_rate = alpha / (beta + N)
```

thereafter. There already was a "number of passes" argument called `-n` or `--npasses`. You can see all of the available command line arguments by running

```
bin/thresh -h
```

Feel free to close or comment on this issue as you see fit and let me know if you have any questions.
